### ISSUE TITLE
ERROR - Exception while initializing

### ISSUE THREAD

**Issue by czoka** [crealitycloud/OctoPrint-CrealityCloud#73]
Plugin version reported by octoprint is 1.0.9 although the latest release (as of writing) should be [1.0.8](https://github.com/crealitycloud/OctoPrint-CrealityCloud/releases)
![image](https://github.com/crealitycloud/OctoPrint-CrealityCloud/assets/11091030/33f99b6e-a87a-4377-9edc-82ad2f09c7cb)

This issue appears only after the key file is uploaded:
```
2024-02-29 08:27:54,832 - octoprint.plugin.core - ERROR - Exception while initializing plugin crealitycloud, disabling it
Traceback (most recent call last):
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint/plugin/core.py", line 1984, in initialize_implementation
    implementation.initialize()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  [Previous line repeated 4 more times]
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/__init__.py", line 37, in initialize
    self._crealitycloud = CrealityCloud(self)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/crealitycloud.py", line 57, in __init__
    self.connect_thingsboard()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/crealitycloud.py", line 182, in connect_thingsboard
    self.thingsboard.client_initialization(region)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/crealitytb.py", line 29, in client_initialization
    self.__client_create()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/crealitytb.py", line 55, in __client_create
    self.client = TBDeviceMqttClient(self._host, self.credentials)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/tb_device_mqtt.py", line 184, in __init__
    self._client = paho.Client()
TypeError: __init__() missing 1 required positional argument: 'callback_api_version'
```

After a complete reinstall of the plugin i get these logs when uploading the key file:
```
2024-02-29 08:51:56,482 - octoprint - ERROR - Exception on /plugin/crealitycloud/status [GET]
Traceback (most recent call last):
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint/vendor/flask_principal.py", line 196, in _decorated
    rv = f(*args, **kw)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/__init__.py", line 122, in get_status
    return {"actived": 0, "iot": False, "printer": False, "country": country}
UnboundLocalError: local variable 'country' referenced before assignment
2024-02-29 08:51:56,621 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.XXX.XXX
2024-02-29 08:51:56,668 - octoprint.server.util.flask - INFO - Passively logging in user redacted_user from ::ffff:192.168.XXX.XXX
2024-02-29 08:51:56,668 - octoprint.access.users - INFO - Logged in user: redacted_user
2024-02-29 08:51:56,857 - octoprint.server.preemptive_cache - INFO - ... done in 1.26s
2024-02-29 08:51:57,710 - octoprint.server.util.sockjs - INFO - User redacted_user logged in on the socket from client ::ffff:192.168.XXX.XXX
2024-02-29 08:52:13,018 - octoprint.plugins.crealitycloud - INFO - {'deviceName': '#######################', 'deviceSecret': '####################', 'iotType': 2, 'region': 5}
2024-02-29 08:52:13,049 - octoprint.plugins.crealitycloud - INFO - start iot server
2024-02-29 08:52:13,049 - octoprint.plugins.crealitycloud - INFO - start connect thingsboard
2024-02-29 08:52:13,058 - octoprint.plugins.crealitycloud - ERROR - __init__() missing 1 required positional argument: 'callback_api_version'
2024-02-29 08:52:13,059 - octoprint - ERROR - Exception on /plugin/crealitycloud/status [GET]
Traceback (most recent call last):
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint/vendor/flask_principal.py", line 196, in _decorated
    rv = f(*args, **kw)
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/__init__.py", line 114, in get_status
    self._crealitycloud.device_start()
  File "/home/redacted_user/oprint/lib/python3.9/site-packages/octoprint_crealitycloud/crealitycloud.py", line 333, in device_start
    self._aliprinter.state = 0
AttributeError: 'NoneType' object has no attribute 'state'
```

If I should provide more information let me know 😄

**Comment by TTACsf** [comment]
I have the same problem. Have you solved it

**Comment by jneilliii** [comment]
try this, SSH to the pi and run this command
```
~/oprint/bin/pip install --force-reinstall "paho-mqtt<2"
```
then restart OctoPrint

**Comment by Nighthawk70** [comment]
> try this, SSH to the pi and run this command
> 
> ```
> ~/oprint/bin/pip install --force-reinstall "paho-mqtt<2"
> ```
> 
> then restart OctoPrint

I had the exact same error and this fixed it. THANK YOU!!!

**Comment by bilinxing** [comment]
The latest version has fixed this issue
